### ISSUE TITLE
Wont Open Just Crashes! Help"

### ISSUE THREAD

**Issue by Fmlad** [Hexeption/Youtube-Hacked-Client-1.8#22]
at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:642)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:475)
	at net.minecraft.client.Minecraft.run(Minecraft.java:394)
	at net.minecraft.client.main.Main.main(Main.java:114)
	at Start.main(Start.java:11)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:252)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:642)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:475)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:394)
	at net.minecraft.client.main.Main.main(Main.java:114)
	at Start.main(Start.java:11)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 878188016 bytes (837 MB) / 1046937600 bytes (998 MB) up to 1046937600 bytes (998 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: mcp
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)

**Comment by Fmlad** [comment]
Help plz

**Comment by Creeperlover234** [comment]
Ok, what you need to do is download this file: https://mega.nz/#F!vsxCXZII!oH5SW-mHuQFdk9YlsMwUVA and when you download this file go to your jar file in your versions folder and drag in the org folder into the main folder when you first open the jar(Where assests and net folder should be) and launch it. If your jar file doesnt have a assests file, open a 1.8 jar file and take the assests file from that and put that in the main area too. Hope this helped!
